/**
 * The single import boundary for TypeScript 7's unstable compiler API.
 */
export {
  LanguageVariant,
  ScriptKind,
  SyntaxKind,
  createScanner,
  isArrayBindingPattern,
  isArrowFunction,
  isBlock,
  isCallExpression,
  isClassDeclaration,
  isEnumDeclaration,
  isElementAccessExpression,
  isExportDeclaration,
  isExpressionStatement,
  isExternalModuleReference,
  isFunctionExpression,
  isFunctionDeclaration,
  isIdentifier,
  isImportDeclaration,
  isImportEqualsDeclaration,
  isImportExpression,
  isInterfaceDeclaration,
  isMethodDeclaration,
  isModuleDeclaration,
  isNamedExports,
  isNamedImports,
  isNamespaceImport,
  isNewExpression,
  isNoSubstitutionTemplateLiteral,
  isObjectBindingPattern,
  isPropertyAccessExpression,
  isPropertyDeclaration,
  isStringLiteral,
  isStringLiteralLikeNode,
  isTypeAliasDeclaration,
  isVariableStatement,
} from "typescript/unstable/ast";
export { createVirtualFileSystem } from "typescript/unstable/fs";
export type { FileSystem } from "typescript/unstable/fs";
export {
  API,
  DiagnosticCategory,
} from "typescript/unstable/sync";

export type {
  ArrowFunction,
  Block,
  CallExpression,
  ClassDeclaration,
  ElementAccessExpression,
  Expression,
  ExpressionStatement,
  FunctionExpression,
  FunctionDeclaration,
  Identifier,
  MethodDeclaration,
  Node,
  NodeArray,
  ParameterDeclaration,
  PropertyAccessExpression,
  PropertyDeclaration,
  Scanner,
  SourceFile,
  Statement,
  StringLiteralLikeNode,
  TypeNode,
} from "typescript/unstable/ast";
export type {
  Checker,
  Diagnostic as TypeScriptDiagnostic,
  Program,
  Project,
  Snapshot,
  Symbol as TypeScriptSymbol,
  Type as TypeScriptType,
} from "typescript/unstable/sync";
