/// implementation.ts — realization entry point for collision.chz.ts (AUTO-GENERATED by chz-realize).
/// Loads human prologue, realized symbols, then human epilogue. Do not edit; re-run `chz realize` instead.

import "./implementations/__prologue__.ts";

export { 충돌판정_2D } from "./implementations/충돌판정_2D.ts";

import "./implementations/__epilogue__.ts";
