/// implementation.ts — realization entry point for phone-number-normalizer.chz.ts (AUTO-GENERATED by chz-realize).
/// Loads human prologue, realized symbols, then human epilogue. Do not edit; re-run `chz realize` instead.

import "./implementations/__prologue__.ts";

export { phoneNumberNormalizer } from "./implementations/phoneNumberNormalizer.ts";

import "./implementations/__epilogue__.ts";
