/// implementation.ts — realization entry point for gomoku.chz.ts (AUTO-GENERATED by chz-realize).
/// Loads human prologue, realized symbols, then human epilogue. Do not edit; re-run `chz realize` instead.

import "./implementations/__prologue__.ts";

export { GomokuGame } from "./implementations/GomokuGame.ts";

import "./implementations/__epilogue__.ts";
