/// implementation.ts — realization entry point for collision.chz.ts (AUTO-GENERATED by chz-realize).
/// Re-exports every realized symbol. Do not edit; re-run `chz realize` instead.

export { 충돌판정_2D } from "./implementations/충돌판정_2D.ts";
