/**
 * Sidecar shim emission (docs/20).
 *
 * A Cheese module's face for the outside world is `example.ts`, never
 * `example.chz.ts` and never a realization path. The shim is the single
 * realize output that plain TypeScript consumers import directly, so it must
 * resolve under nothing but the standard rules every bundler already knows.
 * That is why the re-export specifier carries no file extension: unlike the
 * files inside the realization directory, the shim must not force a tsconfig
 * option (`allowImportingTsExtensions`) onto the consuming project.
 *
 * The content is fully determined by the source file's name and location. No
 * LLM is involved, and the realization directory always sits at the same
 * relative position, so the specifier is a fixed pattern rather than a
 * computed relative path.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

import { realizationBaseName } from "./preprocessor.ts";

/** Header marker identifying a file as an engine-owned shim. */
export const SHIM_MARKER = "AUTO-GENERATED by chz realize";

/** Absolute path of the sidecar shim belonging to a Cheese source file. */
export function shimPath(fileName: string): string {
  return join(dirname(resolve(fileName)), `${realizationBaseName(fileName)}.ts`);
}

/** Deterministic shim content for a Cheese source file. */
export function renderShim(fileName: string): string {
  const base = realizationBaseName(fileName);
  return [
    `/// ${base}.ts — ${SHIM_MARKER}. Do not edit.`,
    `/// The face of ${basename(resolve(fileName))}: consumers import "./${base}",`,
    `/// never the source file and never a realization path (docs/20).`,
    ``,
    `export * from "./chz/realization/${base}/implementation";`,
    ``,
  ].join("\n");
}

/**
 * Preflight for the shim slot, run before any directory is created or any
 * session starts. Both failures are the human's to resolve by renaming, so
 * finding them after a run of LLM sessions would be pure waste.
 */
export function assertShimSlotAvailable(fileName: string): void {
  const path = shimPath(fileName);
  const source = resolve(fileName);
  if (path === source) {
    throw new Error(
      `cannot emit the sidecar shim for '${basename(source)}': the shim would overwrite the source file itself. ` +
        `Name the source '<name>.chz.ts' so the shim can take '<name>.ts' (docs/20).`,
    );
  }
  if (!existsSync(path)) return;
  if (readFileSync(path, "utf8").includes(SHIM_MARKER)) return;
  throw new Error(
    `cannot emit the sidecar shim '${path}': a human-written file already occupies that slot. ` +
      `Rename either that file or '${basename(source)}' so the shim has a free name (docs/20).`,
  );
}

/**
 * Write the shim next to its source file and return the path.
 *
 * The shim is regenerated on every successful realize. v0 records no hash for
 * it, so an unauthorized edit is silently overwritten rather than reported as
 * drift — see the note in docs/20.
 */
export function writeShim(fileName: string): string {
  const path = shimPath(fileName);
  writeFileSync(path, renderShim(fileName), "utf8");
  return path;
}
