/// battle.chz.ts
// An example of one Cheese file importing another: damage calculation.
//
// The rules for using another Cheese module are the same as in plain TypeScript:
// import the shim (`./stats`) generated by realize instead of importing the source
// (`./stats.chz.ts`) directly (doc 20). The import below lets the dependency graph
// discover an edge across file boundaries (doc 62), so realize completes
// `isCriticalHit` before processing this file.

import { isCriticalHit, type CombatStats } from "./stats";

export imagine function calculateDamage(
  attacker: CombatStats,
  defender: CombatStats,
): number {
  requirements(`
    # Calculate final damage based on the attacker's and defender's stats.
    - Calculate base damage using the attacker's attack and the defender's defense.
      You may choose the exact formula.
    - Use \`isCriticalHit\` to determine whether the hit is critical. If it is,
      double the final damage.
    - Final damage must be a non-negative integer.
  `);

  ensure("Final damage is a non-negative integer.", () => {
    const damage = calculateDamage(
      { attack: 10, defense: 5, luck: 0 },
      { attack: 5, defense: 5, luck: 0 },
    );
    assert(Number.isInteger(damage));
    assert(damage >= 0);
  });

  ensure("Luck 100 (always critical) does not deal less damage than luck 0.", () => {
    const defender: CombatStats = { attack: 5, defense: 5, luck: 0 };
    const normalDamage = calculateDamage({ attack: 10, defense: 5, luck: 0 }, defender);
    const criticalDamage = calculateDamage({ attack: 10, defense: 5, luck: 100 }, defender);
    assert(criticalDamage >= normalDamage);
  });
}
